version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: greenhouse-api
    ports:
      - "5000:8080"

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Data Source=/data/greenhouse.db

    volumes:
      - ./server/data:/data